name: Build and Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Adjust the timeout as needed

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.10.0'  # Adjust the Node.js version as needed

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Update Vercel CLI
        run: npm install -g vercel@latest

      - name: Deploy to Vercel
        if: github.ref == 'refs/heads/main'
        run: npx vercel --token ${{ secrets.VERCEL_TOKEN }} --confirm
